freebsd_instance:
  image_family: freebsd-12-1-snap

task:
  env:
    GTEST_SHUFFLE: 1
    GTEST_RUNTIME_LIMIT: 99
  install_script: pkg install -y cmake git base64
  script: |
    git fetch --tags --prune
    git submodule foreach --recursive git fetch --unshallow --tags --prune
    cmake --version
    cmake . &&  cmake --build . -- -k && (ctest || \
       (echo "-------------------------------------------------------------------------------"; \
       xz -c -9 Testing/Temporary/LastTest.log | base64 && \
       echo "-------------------------------------------------------------------------------"; \
       exit 1) \
    ) && \
    externals/libfptu/test/fptu_c_mode && test/fpta_c_mode
