language: cpp
sudo: false
dist: trusty
cache: bundler

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libgtest-dev

compiler:
  - gcc
  - clang

os:
  - linux

env:
  global:
    - GTEST_SHUFFLE=1
    - GTEST_RUNTIME_LIMIT=142

script:
  - git fetch --tags --prune
  - git submodule foreach --recursive git fetch --tags --prune
  - cmake --version
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then cmake . && make all && make test; fi
