version: 0.1.3.{build}

environment:
  GTEST_SHUFFLE: 1
  GTEST_RUNTIME_LIMIT: 142
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      TOOLSET: v141
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      TOOLSET: v140

branches:
  except:
    - coverity_scan

configuration:
- Debug
- Release

platform:
- x86
- x64

artifacts:
  - path: '_build/Testing/Temporary/*'
    name: test_results

install:
- git submodule sync
- git submodule update --init --recursive
- git fetch --tags --prune
- git submodule foreach --recursive git fetch --tags --prune
- cmake --version
- ps: choco install windbg

before_build:
- ps: |
    Write-Output "*******************************************************************************"
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    $generator = $env:CMAKE_GENERATOR
    if ($env:PLATFORM -eq "x64") {
        $generator = "$generator Win64"
    }
    Write-Output "Toolchain: $generator ($env:TOOLSET)"
    Write-Output "*******************************************************************************"

build_script:
- ps: |
    md _build -Force | Out-Null
    cd _build

    & cmake -G "$generator" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    Write-Output "*******************************************************************************"

    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    Write-Output "*******************************************************************************"

test_script:
- ps: |-
    New-Item -Path "HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Force
    New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps' `
      -Name DumpType -Value 2 -PropertyType DWORD -Force
    New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps' `
      -Name DumpCount -Value 42 -PropertyType DWORD -Force
    New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps' `
      -Name DumpFolder -Value "$($env:LOCALAPPDATA)\CrashDumps" -PropertyType STRING -Force
- ps: |
    & ctest -C $env:CONFIGURATION --output-on-failure
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & externals/libfptu/test/$env:CONFIGURATION/fptu_c_mode.exe
    & test/$env:CONFIGURATION/fpta_c_mode.exe

on_failure:
- ps: |-
    $symPath = 'SRV*c:\symbols\*http://msdl.microsoft.com/download/symbols'
    $files = Get-ChildItem -Path "$($env:LOCALAPPDATA)\CrashDumps"
    ForEach ($file in $files) {
      Write-Output "Analyzing crash dump: $file"
      "C:\Program Files (x86)\Windows Kits\10\Debuggers\$($env:PLATFORM)\cdb.exe" `
        -y $symPath -z $file -c '!analyze -v; q'
    }
