version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - run: make all
      - run: ulimit -c unlimited && make check
      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv -t /tmp/artifacts core.*
          when: on_fail
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
