version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run: make all
      - run: ulimit -c unlimited && make check
      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv -t /tmp/artifacts core.*
          when: on_fail
      - run:
          command: >
            if which clang-format-6.0 > /dev/null && make reformat && [[ -n $(git diff) ]];
              then
                echo "You must run 'make reformat' before submitting a pull request";
                echo "";
                git diff;
                exit -1;
            fi
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
