version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:20.04
    steps:
      - checkout
      - run:
          command: |
            ulimit -c unlimited
            make all check
      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv -t /tmp/artifacts core.*
          when: on_fail
      - run:
          command: >
            if make reformat && [[ -n $(git diff) ]];
              then
                echo "You must run 'make reformat' before submitting a pull request";
                echo "";
                git diff;
                exit -1;
            fi
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
