version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    environment:
      GTEST_SHUFFLE: 1
      GTEST_RUNTIME_LIMIT: 142
    steps:
      - run: sudo apt update -q && sudo apt install cmake libgtest-dev clang-format-6.0 valgrind
      - checkout
      - run:
          command: |
            git fetch--unshallow || true
            git fetch --tags --prune
      - run:
          command: |
            git submodule sync
            git submodule update --init --recursive
            git submodule foreach --recursive git fetch --tags --prune
      - run:
          command: |
            c++ --version
            cmake --version
      - run: cmake .
      - run: make --keep-going all
      - run:
          command: |
            ulimit -c unlimited
            make --keep-going test
            externals/libfptu/test/fptu_c_mode
            test/fpta_c_mode
      - run:
          command: |
            mkdir -p /tmp/artifacts
            mv -t /tmp/artifacts core.*
          when: on_fail
      - run:
          command: |
            if which clang-format-6.0 > /dev/null && make reformat && [[ -n $(git diff) ]]; then
              echo "You must run 'make reformat' before submitting a pull request"
              echo ""
              git --no-pager diff
              exit -1
            fi
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
