language: c
dist: focal

arch:
  - amd64
  - arm64
#  - ppc64le ## travis-ci.org 2020-06-25: An error occurred while generating the build script.
  - s390x
  - arm64-graviton2

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      env: T1HA_EXTRA_CFLAGS="-DT1HA_USE_INDIRECT_FUNCTIONS=1"
    - os: linux
      env: T1HA_EXTRA_CFLAGS="-DT1HA_USE_INDIRECT_FUNCTIONS=0"

env:
  global:
    - secure: "fQvkBkC9lpnhl6L9DsfXQWBaHR4UMR1wtLjPrSn7Sl8cwKfJ5MAR+K1Khz7BDkKV7MCN6no7QJ1MYbwSSp67XnvwWL10yt/KbaAZCMNRWgwenfiCvdN67sw4rliX3q3X6PllI2jUSJy8gFmHDZzqEH4ark6uq3Gb30gt2lSlxXd/vF4xDOjy/IyLhzbFQIhJScHLApxeOYuoHLEmta5gsXjwhK6dsftDAHGc6alyPu19h5p4wvv+bP2WcREvMQHK6u3vfeUrUGdNYboEHyJmM9qHnR7JPmGMEhuF/lWjc7DtWrvb5qAVSayeKbTOQWnk5sINN46mTEDfGXkHsjlFIau6mdIGDNIAhdge6ODuVyCTS4pTd0LQNTJG5pL0dFDTtiqaSkDU4M0/ofsO2O535dwFhdJz7qqqWacTYDJCPGvku1TmhfxNWyrFlp/I8shtYdMKmNtHQrtEBlLYCdnypow2VB+3tyvwve5LpwSY2BD7gY2NrP6fp7vHqfoan5PXfsxXuBt7LJDmHDBOvTils2RPbqiF0jG1Xk1YYWTUopLqEl2iYUqnOeg4XcS7wEwOpgbEqfrvHJ4BPUI+Rz1TMN19P9sgWS+hWuUMg+hka3ZVvzAI619eqzMnYVNTJjbDHZya3kSxfBuyO7RLjj+3UN88QClLoIKJ7Aa/50xZGY8="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    update: true

before_script: |
  if [ "${TRAVIS_BRANCH}" = "coverity_scan" ]; then
    # call Coverity Scan manually of addons.coverity_scan for first job only
    if [ "${TRAVIS_JOB_NUMBER}" = "${TRAVIS_BUILD_NUMBER}.1" ]; then
      export COVERITY_SCAN_BRANCH=1
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' -o coverity_scan.sh
    else
      echo 'echo "Skip CoverityScan for unrelated os/compiler"' > coverity_scan.sh
    fi
  fi

script: |
  git fetch --unshallow --tags --prune --force
  git submodule foreach --recursive git fetch --unshallow --tags --prune --force
  if [ ! -s ./coverity_scan.sh ]; then
    make --keep-going all && \
    MALLOC_CHECK_=7 MALLOC_PERTURB_=42 make check && \
    if [ "$(uname -m)" = "x86_64" -a -z "${T1HA_EXTRA_CFLAGS}" ] && sudo apt-get install g++-multilib; then
      export T1HA_EXTRA_CFLAGS="-m32"
      make clean && \
      make --keep-going all && \
      MALLOC_CHECK_=7 MALLOC_PERTURB_=42 make check
    fi
  else
    COVERITY_SCAN_PROJECT_NAME="leo-yuriev/t1ha" \
    COVERITY_SCAN_NOTIFICATION_EMAIL="leo@yuriev.ru" \
    COVERITY_SCAN_BUILD_COMMAND_PREPEND="" \
    COVERITY_SCAN_BUILD_COMMAND="make all" \
    COVERITY_SCAN_BRANCH_PATTERN="$TRAVIS_BRANCH" \
      bash ./coverity_scan.sh || cat cov-int/scm_log.txt
  fi

after_script: |
  if [ "${TRAVIS_BRANCH}" != "coverity_scan" -a "${TRAVIS_JOB_NUMBER}" = "${TRAVIS_BUILD_NUMBER}.1" ] && \
      git rm -rf test/highwayhash test/stadtx test/wyhash test/xxhash && \
      make reformat && [[ -n $(git diff) ]]; then
    echo "You must run 'make reformat' before submitting a pull request"
    echo "-------------------------------------------------------------------------------"
    git diff
    sleep 1
    echo "-------------------------------------------------------------------------------"
    sleep 1
    exit -1
  fi
  echo "-------------------------------------------------------------------------------"
  sleep 1
